version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosec
    - misspell
    - gocyclo
    - bodyclose
    - copyloopvar
    - errname
    - errorlint
    - modernize
    - nilerr
    - prealloc
    - unconvert
    - unparam
    - usestdlibvars
  settings:
    errcheck:
      check-type-assertions: true
    gocyclo:
      min-complexity: 20
    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment
    misspell:
      locale: US
      ignore-rules:
        - darcula
    staticcheck:
      checks:
        - all
        - -ST1000
  exclusions:
    generated: strict
    presets:
      - comments
      - std-error-handling
      - common-false-positives
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - gosec
          - unparam
      - linters:
          - gosec
        text: "G103|G117|G204"
      - linters:
          - modernize
        text: "stringsseq"

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      colors: true
  sort-order:
    - linter
    - file

run:
  timeout: 3m
  tests: true